// src/redux/actionTypes.js
export const FETCH_SOCIAL_MEDIA = 'FETCH_SOCIAL_MEDIA';
export const FETCH_PROVIDER_DATA ='FETCH_PROVIDER_DATA'
export const FETCH_GAME_CATEGORY ='FETCH_GAME_CATEGORY'
export const PAYMENT_CURRENCY="PAYMENT_CURRENCY"
export const GET_SINGLE_USERDETAILS="GET_SINGLE_USERDETAILS"
export const SHOW_SIDEBAR="SHOW_SIDEBAR"
export const HALF_SIDEBAR="HALF_SIDEBAR"
export const OPEN_SECOND_SIDEBAR="OPEN_SECOND_SIDEBAR"
export const SET_HIDE_FIRST_SIDEBAR="SET_HIDE_FIRST_SIDEBAR"
export const SET_BACK_SECOND_SIDEBARITEM="SET_BACK_SECOND_SIDEBARITEM"
export const SET_ACTIVE_BOTTOM_TAB="SET_ACTIVE_BOTTOM_TAB"
export const SET_MULTIPLE_CATEGORY_FOR_FILTER="SET_MULTIPLE_CATEGORY_FOR_FILTER"
export const CHECK_APPLY_FILTERS='CHECK_APPLY_FILTERS'
export const SET_QUERY_FOR_SEARCH='SET_QUERY_FOR_SEARCH'




